setw -g mode-keys vi

unbind   C-o
bind     C-o select-pane -t :.+
bind     =   select-layout -E

bind -T prefix j select-pane -D
bind -T prefix k select-pane -U
bind -T prefix h select-pane -L
bind -T prefix l select-pane -R
bind -T prefix a select-layout even-horizontal
bind -T prefix A select-layout even-vertical
bind -T prefix _ resize-pane -y 999
bind -T prefix | resize-pane -x 999

set-window-option -g window-active-style bg=terminal
set-window-option -g window-style bg=black

set -g status-style bg=$TMUX_STATUS_BG_COLOR,fg=$TMUX_STATUS_FG_COLOR
set -g window-status-current-format "#[bg=$TMUX_ACTIVE_BG_COLOR]#[fg=$TMUX_ACTIVE_FG_COLOR][#I:#W#{?window_zoomed_flag,🔍 ,}]#[default]"
set -g window-status-format '[#I:#W#{?window_zoomed_flag,🔍 ,}]'
set -g window-status-separator " "

set -g status-right "[ #H ]"
set -g status-left "[ 🏠 ] "
